spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/story_admin?useSSL=false&allowMultiQueries=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  redis:
    database: 0
    host: 192.168.99.100
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 200
        max-wait: 3000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: story_admin_log
  mail:
    host: smtp.163.com
    username: aaaa@163.com
    password: 111111
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
file:
  multipart:
    #文件上传
    autoSaveEnabled: true
    baseDir: D:/upload/
# 备份
dbbackup:
  servername: 127.0.0.1
  dbname: story_admin
  username: root
  password: 123456
  installPath: ${file.upload:D:/Development/mysql-8.0.13-winx64}
  backupPath: ${file.export:D:/Backup}

# 日志相关
logging:
  file: d:/storyadmin.log #开发环境系统存放日志文件的目录
  level:
    com:
      story:
        storyadmin: debug #设置日志数据级别
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p})
      %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} [%15.15X{username}]
      [%15.15X{ip}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

